# Generated by Django 4.1.3 on 2022-11-22 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Residence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Título")),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("price", models.FloatField(verbose_name="Preço")),
                ("street", models.TextField(verbose_name="Rua")),
                ("district", models.TextField(verbose_name="Bairro")),
                (
                    "number",
                    models.CharField(blank=True, default="", max_length=5, null=True),
                ),
                ("complement", models.TextField(verbose_name="Complemento")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bathrooms",
                    models.PositiveIntegerField(verbose_name="Quantidade de banheiros"),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(verbose_name="Quantidade de quartos"),
                ),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="residences/pictures/%Y/%m/%d/")),
                (
                    "residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="residences.residence",
                        verbose_name="Residência",
                    ),
                ),
            ],
        ),
    ]
