# Generated by Django 4.1.3 on 2022-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publicado"),
        ),
        migrations.AlterField(
            model_name="residence",
            name="complement",
            field=models.TextField(default="", verbose_name="Complemento"),
        ),
    ]
