# Generated by Django 4.1.3 on 2022-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0002_residence_is_published_alter_residence_complement"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="city",
            field=models.CharField(default="São Raimundo Nonato", max_length=50),
        ),
        migrations.AlterField(
            model_name="residence",
            name="description",
            field=models.TextField(verbose_name="Descrição da residência"),
        ),
        migrations.AlterField(
            model_name="residence",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=5, null=True, verbose_name="Número"
            ),
        ),
    ]
