# Generated by Django 4.1.3 on 2022-11-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0003_residence_city_alter_residence_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="zipcode",
            field=models.CharField(default="64770000", max_length=20),
        ),
    ]
