# Generated by Django 4.1.3 on 2022-11-22 16:48

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", accounts.models.UserManager()),],
        ),
    ]
